### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 31

### ISSUE THREAD

**Issue by badboycxcc** [Like0x/0xagent#2]
[+] Patch exit
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 31
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at common.Authorization.hex2bytes(Unknown Source)
        at common.Authorization.<init>(Unknown Source)
        at server.TeamServer.main(Unknown Source)

**Comment by Like0x** [comment]
Please provide startup parameters and a possible way to reproduce your error.
