### ISSUE TITLE
Trapped java.lang.IllegalArgumentException during manage user [Manage: neo]: No location for 'Characteristics'

### ISSUE THREAD

**Issue by cinasea123** [Like0x/0xagent#3]
for cs4.5 teamserver error No location for 'Characteristics'

**Comment by c4ln** [comment]
←[01;33m[!]←[0m Trapped java.io.EOFException during client  read [TeamQueue Reader]: null
 Trapped java.lang.IllegalArgumentException during manage user [Manage: neo]: No location for 'Characteristics'
java.lang.IllegalArgumentException: No location for 'Characteristics'

**Comment by Like0x** [comment]
Please provide startup parameters and a possible way to reproduce your error.

**Comment by CodeXTF2** [comment]
I get this too

**Comment by Byc4i** [comment]
java.lang.RuntimeException: Header e_magic Magic Failed: 0 expected (23117)
        at pe.PEParser.error(Unknown Source)
        at pe.PEParser.header(Unknown Source)
        at pe.PEParser.parse(Unknown Source)
        at pe.PEParser.<init>(Unknown Source)
        at pe.PEParser.load(Unknown Source)
        at pe.PEEditor.getInfo(Unknown Source)
        at pe.PEEditor.checkAssertions(Unknown Source)
        at pe.MalleablePE.pre_process(Unknown Source)
        at c2profile.Preview.getPE(Unknown Source)
        at c2profile.Preview.summarize(Unknown Source)
        at server.ManageUser.process(Unknown Source)
        at server.ManageUser.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:829)
[-] Trapped java.lang.IllegalArgumentException during manage user [Manage: dhcat]: No location for 'Characteristics'
java.lang.IllegalArgumentException: No location for 'Characteristics'
        at pe.PEParser.getLocation(Unknown Source)
        at pe.PEEditor.setCharacteristic(Unknown Source)
        at pe.PEEditor.setRWXHint(Unknown Source)
        at pe.MalleablePE.pre_process(Unknown Source)
        at c2profile.Preview.getPE(Unknown Source)
        at c2profile.Preview.summarize(Unknown Source)
        at server.ManageUser.process(Unknown Source)
        at server.ManageUser.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by innxrmxst** [comment]
same
